apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: gumroad-staging

resources:
  - ../../base

images:
  - name: gumroad/ping-delivery
    newName: ghcr.io/thiagodiniz/ping-delivery
    newTag: latest

patches:
  - target:
      kind: Deployment
      name: ping-delivery
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
  - target:
      kind: HorizontalPodAutoscaler
      name: ping-delivery
    patch: |-
      - op: replace
        path: /spec/minReplicas
        value: 1
