apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: gumroad-staging

resources:
  - ../../base

images:
  - name: gumroad/tax-id-validation
    newName: gumroad/tax-id-validation
    newTag: latest

patches:
  - target:
      kind: Deployment
      name: tax-id-validation
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
  - target:
      kind: HorizontalPodAutoscaler
      name: tax-id-validation
    patch: |-
      - op: replace
        path: /spec/minReplicas
        value: 1
